<?xml version="1.0"?>
<Globalsettings>
  <Settings>
    <CommonInformation>
      <SolutionTitle>Wrap Dynamicweb</SolutionTitle>
      <Partner>Dynamicweb A/S</Partner>
      <Email>noreply@dynamicweb.dk</Email>
      <CopyrightMetaInformation>Build by Dynamicweb</CopyrightMetaInformation>
      <SolutionID>310a9249-3daa-4094-bebe-03fb250dd5af</SolutionID>
      <SolutionLastReportDate>2016-6-3 21:34:36</SolutionLastReportDate>
      <SolutionLastFileSizeReportDate>2016-6-3 21:34:34</SolutionLastFileSizeReportDate>
      <InstallationCrmID>cb8b2d33-c229-e611-aba9-00155d4f8211</InstallationCrmID>
      <InstallationCheckSum>9626d1b2a4966d70e15899ccb46c6d82</InstallationCheckSum>
      <SolutionFilesize>123906</SolutionFilesize>
      <SolutionDatabaseSize>1033</SolutionDatabaseSize>
      <SolutionLoginInfoLogo>../Images/logo-dynamicweb.png</SolutionLoginInfoLogo>
      <PartnerEmail>info@dynamicweb.dk</PartnerEmail>
      <SolutionLoginInfo>Created by Dynamicweb A/S</SolutionLoginInfo>
      <SolutionLoginInfoLogo_path>/Files/Images/logo-dynamicweb.png</SolutionLoginInfoLogo_path>
      <InstallationCrmSolutionName>
      </InstallationCrmSolutionName>
      <InstallationCrmSolutionID>
      </InstallationCrmSolutionID>
    </CommonInformation>
    <TextEditor>
      <Format>Heading</Format>
      <Paste>
      </Paste>
      <ColorsAndFonts>True</ColorsAndFonts>
      <ActivateWordEditing>False</ActivateWordEditing>
      <ExtendedFormating>True</ExtendedFormating>
      <Type>default</Type>
      <NewEditor>
        <UseStylesheet>True</UseStylesheet>
        <Source>True</Source>
        <Preview>True</Preview>
        <Templates>True</Templates>
        <Print>True</Print>
        <SpellCheck>True</SpellCheck>
        <UniversalKey>True</UniversalKey>
        <Cut>True</Cut>
        <Copy>True</Copy>
        <Paste>True</Paste>
        <PasteText>True</PasteText>
        <PasteWord>True</PasteWord>
        <Undo>True</Undo>
        <Redo>True</Redo>
        <Find>True</Find>
        <Replace>True</Replace>
        <SelectAll>True</SelectAll>
        <Link>True</Link>
        <Unlink>True</Unlink>
        <Anchor>True</Anchor>
        <Image>True</Image>
        <Table>True</Table>
        <Rule>True</Rule>
        <SpecialChar>True</SpecialChar>
        <Bold>True</Bold>
        <Italic>True</Italic>
        <Underline>True</Underline>
        <StrikeThrough>True</StrikeThrough>
        <Subscript>True</Subscript>
        <Superscript>True</Superscript>
        <RemoveFormat>True</RemoveFormat>
        <JustifyLeft>True</JustifyLeft>
        <JustifyCenter>True</JustifyCenter>
        <JustifyRight>True</JustifyRight>
        <JustifyFull>True</JustifyFull>
        <OrderedList>True</OrderedList>
        <UnorderedList>True</UnorderedList>
        <Outdent>True</Outdent>
        <Indent>True</Indent>
        <Style>True</Style>
        <FontName>True</FontName>
        <FontSize>True</FontSize>
        <TextColor>True</TextColor>
        <BGColor>True</BGColor>
        <EnterType>br</EnterType>
        <FitWindow>True</FitWindow>
        <Flash>True</Flash>
        <Blockquote>True</Blockquote>
        <DwPageLink>True</DwPageLink>
        <GoogleTranslate>False</GoogleTranslate>
      </NewEditor>
      <EditorVersion>EditorNew</EditorVersion>
      <EditorHeight>500</EditorHeight>
      <EditorWidth>580</EditorWidth>
      <UseProviderBasedEditors>True</UseProviderBasedEditors>
    </TextEditor>
    <Paragraph>
      <MaximumLockingInMinutes>15</MaximumLockingInMinutes>
      <SpacesBeforeParagraph>0</SpacesBeforeParagraph>
      <FrontendEditingEnabled>False</FrontendEditingEnabled>
      <SpaceMode>none</SpaceMode>
      <HideSpaceSetting>True</HideSpaceSetting>
      <EnableAlignmentOnParagraphImages>False</EnableAlignmentOnParagraphImages>
      <RequireAltAndTitle>False</RequireAltAndTitle>
      <DisableStandard>False</DisableStandard>
    </Paragraph>
    <Performance>
      <AllNavigationImagesInTheSameJavascript>False</AllNavigationImagesInTheSameJavascript>
      <ActivateDublinCore>False</ActivateDublinCore>
      <ActivateMouseoverTextsOnMenuItems>False</ActivateMouseoverTextsOnMenuItems>
      <ActivateTitleTextsOnMenuItems>False</ActivateTitleTextsOnMenuItems>
      <DeactivateBrowserCache>False</DeactivateBrowserCache>
      <DeactivateParagraphAnchor>True</DeactivateParagraphAnchor>
      <ActivateDropDownCache>False</ActivateDropDownCache>
    </Performance>
    <CustomerAccess>
      <LockStylesheet>False</LockStylesheet>
      <LockTemplateFolder>False</LockTemplateFolder>
      <LockNavigationFolder>False</LockNavigationFolder>
      <LockSystemFolder>False</LockSystemFolder>
      <ShowAreabox>False</ShowAreabox>
      <LockDeveloperTools>False</LockDeveloperTools>
      <LockMgmtCenter>False</LockMgmtCenter>
      <HideRememberFeatures>False</HideRememberFeatures>
    </CustomerAccess>
    <MyPage>
      <HideStat>False</HideStat>
      <CustomInfoBoxURLLocation>
      </CustomInfoBoxURLLocation>
    </MyPage>
    <PageNotFound>
      <RedirectTo>
      </RedirectTo>
    </PageNotFound>
    <DynamicwebLoginUrl>www.dynamicweb.dk</DynamicwebLoginUrl>
    <IE8>
      <Mode>IE8Standards</Mode>
    </IE8>
    <Page>
      <Edit>
        <ShowLogoAlt>False</ShowLogoAlt>
        <DisablePopupCalendar>False</DisablePopupCalendar>
      </Edit>
      <ContentTypes>text/html,application/atom+xml,text/css,text/javascript,image/jpeg,application/json,application/pdf,application/rss+xml; charset=ISO-8859-1,text/plain,text/xml</ContentTypes>
      <DisableStandard>False</DisableStandard>
    </Page>
    <ContentEditor>
      <UseNew>True</UseNew>
      <ParagraphList>
        <ShowUpdatedDate>True</ShowUpdatedDate>
        <ShowUpdatedUser>True</ShowUpdatedUser>
        <ShowValidTo>False</ShowValidTo>
        <ShowValidFrom>False</ShowValidFrom>
      </ParagraphList>
      <Metadata>
        <Level1>None</Level1>
        <Level2>None</Level2>
        <Level3>None</Level3>
      </Metadata>
      <UseSimpleParagraphList>False</UseSimpleParagraphList>
      <UseNavigationCancel>False</UseNavigationCancel>
    </ContentEditor>
    <NewsletterSubscription>
      <SaveSetting>newsletterextended</SaveSetting>
    </NewsletterSubscription>
    <GoogleAPI>
      <jQueryUI>False</jQueryUI>
      <jQuery>False</jQuery>
      <SWFObject>False</SWFObject>
      <MooTools>False</MooTools>
      <ScriptAculoUs>False</ScriptAculoUs>
      <Prototype>False</Prototype>
    </GoogleAPI>
    <DwInclude>
      <DisablePerformanceComment>True</DisablePerformanceComment>
      <DisableHrefNameParser>False</DisableHrefNameParser>
      <DisableDwscript>False</DisableDwscript>
      <EnablePageAndParagraphCompatibilityParsing>False</EnablePageAndParagraphCompatibilityParsing>
    </DwInclude>
    <Designs>
      <IgnoreAllModuleJsAndCss>False</IgnoreAllModuleJsAndCss>
      <UseOnlyDesignsAndLayouts>True</UseOnlyDesignsAndLayouts>
      <DoNotIncludeBaseHref>False</DoNotIncludeBaseHref>
      <OptimizeNavigationXml>True</OptimizeNavigationXml>
    </Designs>
    <Logging>
      <Disable71Logging>False</Disable71Logging>
    </Logging>
    <Updates>
      <DisableTemplateUpdates>False</DisableTemplateUpdates>
    </Updates>
    <LastSeenVersion>
      <Version>8.7.2.8</Version>
      <User>
        <UserName>
        </UserName>
      </User>
    </LastSeenVersion>
    <Dictionary>
      <HideOldTranslationButton>false</HideOldTranslationButton>
    </Dictionary>
    <ImageHandler>
      <Width>250</Width>
      <Height>250</Height>
      <ColorSpace>RGB</ColorSpace>
      <Crop>5</Crop>
      <Format>jpg</Format>
      <Compression>75</Compression>
      <Colors>256</Colors>
      <Resolution>72</Resolution>
      <DoNotUpscale>False</DoNotUpscale>
      <ForceDownload>False</ForceDownload>
      <Filename>
      </Filename>
    </ImageHandler>
    <ProviderBasedEditor>
      <EcomDescriptionEditorConfigID>1</EcomDescriptionEditorConfigID>
      <EcomTeaserEditorConfigID>1</EcomTeaserEditorConfigID>
    </ProviderBasedEditor>
    <Pdf>
      <PageSize>
      </PageSize>
    </Pdf>
    <CookieManager>
      <DisableTrackingCookies>False</DisableTrackingCookies>
      <DeleteJsTrackingCookies>False</DeleteJsTrackingCookies>
      <UserNotification>False</UserNotification>
      <ShowWarnings>True</ShowWarnings>
      <WarningTemplate>TopPageWarning.html</WarningTemplate>
      <TrackingCookies>Dynamicweb.VisitorID,Dynamicweb.VisitDate</TrackingCookies>
      <CookieLifetime>365</CookieLifetime>
    </CookieManager>
  </Settings>
  <Modules>
    <Sms>
      <GatewayEmail>{0}.solo@email2sms.dk</GatewayEmail>
      <CopySmsToEmail>np@dynamicweb.dk</CopySmsToEmail>
    </Sms>
    <Filemanager>
      <Upload>
        <Format>activex</Format>
        <FilesPrForm>5</FilesPrForm>
        <MaxFileSize>100</MaxFileSize>
        <ReplaceSpace>False</ReplaceSpace>
        <LatinNormalize>False</LatinNormalize>
      </Upload>
      <FilesPrPage>150</FilesPrPage>
      <FilesInDropdown>150</FilesInDropdown>
      <UseImageglue>Standard</UseImageglue>
      <RememberFolder>
        <Timeout>500</Timeout>
      </RememberFolder>
      <AutoResize>
        <JpegCompression>90</JpegCompression>
        <GifColors>256</GifColors>
      </AutoResize>
      <Templates>
        <HideNotInstalled>False</HideNotInstalled>
      </Templates>
      <UseSimpleFileEditor>False</UseSimpleFileEditor>
      <Thumbnails>
        <KeepOriginalFormatAsPostfix>False</KeepOriginalFormatAsPostfix>
      </Thumbnails>
      <AllowedFolders>500</AllowedFolders>
    </Filemanager>
    <Stylesheet>
      <Color>
        <WindowsColor>True</WindowsColor>
        <WebSafeColors>True</WebSafeColors>
      </Color>
      <BackgroundColor>True</BackgroundColor>
      <Settings>
        <FlashVersion>8</FlashVersion>
        <FlashWmode>Opaque</FlashWmode>
        <DontUseDwCSS>False</DontUseDwCSS>
      </Settings>
    </Stylesheet>
    <Shop>
      <Integration>
        <FTPPath>
        </FTPPath>
        <IntegrationImportTypes>
        </IntegrationImportTypes>
        <IntegrationExportTypes>
        </IntegrationExportTypes>
      </Integration>
      <Price>
        <Round>False</Round>
      </Price>
      <Edit>
        <DeactivateGroups>False</DeactivateGroups>
      </Edit>
    </Shop>
    <Users>
      <PasswordExpireDays>never</PasswordExpireDays>
      <ReusePassword>
        <AfterNumberOfTimes>0</AfterNumberOfTimes>
        <AfterNumberOfDays>allways</AfterNumberOfDays>
      </ReusePassword>
      <PasswordSecurity>low</PasswordSecurity>
      <MinimumOfCharacters>0</MinimumOfCharacters>
      <PasswordMode>show</PasswordMode>
      <NumberOfLines>12</NumberOfLines>
      <UseInAdministration>False</UseInAdministration>
      <EncryptPassword>False</EncryptPassword>
      <UseExtendedComponent>False</UseExtendedComponent>
      <WithSearchOption>False</WithSearchOption>
      <SecureFolderName>Integration</SecureFolderName>
      <AutoLoginCookie>
        <ValideForDays>
        </ValideForDays>
      </AutoLoginCookie>
      <EncryptPasswordHash>MD5</EncryptPasswordHash>
    </Users>
    <Extranet>
      <PasswordExpireDays>never</PasswordExpireDays>
      <ReusePassword>
        <AfterNumberOfTimes>0</AfterNumberOfTimes>
        <AfterNumberOfDays>allways</AfterNumberOfDays>
      </ReusePassword>
      <PasswordSecurity>low</PasswordSecurity>
      <MinimumOfCharacters>0</MinimumOfCharacters>
      <UseWithExtranet>show</UseWithExtranet>
      <EncryptPassword>encrypt</EncryptPassword>
      <EncryptPasswordHash>MD5</EncryptPasswordHash>
    </Extranet>
    <LanguagePack>
      <DefaultLanguage>2</DefaultLanguage>
    </LanguagePack>
    <Audit>
      <DifferentiatePagesParagraphs>False</DifferentiatePagesParagraphs>
    </Audit>
    <Paygate>
      <DOBS>
        <MerchantID>
        </MerchantID>
        <Currency>Ikke valgt</Currency>
      </DOBS>
      <DIBS>
        <MerchantID>
        </MerchantID>
        <Currency>Ikke valgt</Currency>
        <ControlKey1>
        </ControlKey1>
        <ControlKey2>
        </ControlKey2>
        <WindowColor>Blue</WindowColor>
      </DIBS>
    </Paygate>
    <Dynamicdoc>
      <License>
        <Users>
        </Users>
        <Templates>
        </Templates>
      </License>
      <Pitstop>
        <PitstopPath>
        </PitstopPath>
      </Pitstop>
    </Dynamicdoc>
    <Cart>
      <VAT>False</VAT>
    </Cart>
    <NewsletterExtended>
      <MailServer>
        <SMTPport>
        </SMTPport>
        <CDOPort>
        </CDOPort>
        <Timeout>
        </Timeout>
      </MailServer>
      <DropboxAndPickup>
        <DropboxPath>
        </DropboxPath>
      </DropboxAndPickup>
      <Lists>
        <NumberOfRowsInLists>
        </NumberOfRowsInLists>
      </Lists>
    </NewsletterExtended>
    <SearchExtended>
      <IndexCatalog>
      </IndexCatalog>
      <MinimumOfCharacters>
      </MinimumOfCharacters>
    </SearchExtended>
    <Statistics>
      <RemoteHostVariable>
      </RemoteHostVariable>
      <DisablePageStatistics>False</DisablePageStatistics>
      <DisableStatistics>False</DisableStatistics>
    </Statistics>
    <Integration>
      <UserType>1</UserType>
    </Integration>
    <Metadata>
      <Extended>0</Extended>
    </Metadata>
    <OMC>
      <LeadStates>Received a call,Email sent</LeadStates>
      <LeadsListPayload>0</LeadsListPayload>
      <Notifications>
        <ReportsSendInterval>7</ReportsSendInterval>
        <ReportsSendFrom>3</ReportsSendFrom>
        <ReportsSendTo>5</ReportsSendTo>
        <ReturningVisitorsSendTo>5</ReturningVisitorsSendTo>
        <ReturningVisitorsSendFrom>3</ReturningVisitorsSendFrom>
        <ReturningVisitorsSendInterval>1</ReturningVisitorsSendInterval>
        <SplitTestsSendInterval>7</SplitTestsSendInterval>
        <SplitTestsSendFrom>3</SplitTestsSendFrom>
        <SplitTestsSendTo>5</SplitTestsSendTo>
        <SplitTestsSendCRThreshold>5</SplitTestsSendCRThreshold>
        <SplitTestsSendImprovementLimit>20</SplitTestsSendImprovementLimit>
        <ReturningVisitorsLastSent>22-09-2015 03:31:10</ReturningVisitorsLastSent>
      </Notifications>
      <VisitorEngagement>
        <TimeFrame>14</TimeFrame>
        <Pageviews>15</Pageviews>
        <PageviewsPoints>5</PageviewsPoints>
        <NumberOfVisits>10</NumberOfVisits>
        <NumberOfVisitsPoints>7</NumberOfVisitsPoints>
        <LastVisit>2</LastVisit>
        <LastVisitPoints>8</LastVisitPoints>
        <SearchContains>
        </SearchContains>
        <SearchContainsPoints>
        </SearchContainsPoints>
        <InteractionSubmitForm>9</InteractionSubmitForm>
        <InteractionPlaceOrder>10</InteractionPlaceOrder>
        <InteractionViewProduct>8</InteractionViewProduct>
        <InteractionDownloadFile>7</InteractionDownloadFile>
        <InteractionSearch>6</InteractionSearch>
        <InteractionViewNews>5</InteractionViewNews>
        <InteractionUnknown>
        </InteractionUnknown>
        <InteractionAddToCart>
        </InteractionAddToCart>
        <Disable>False</Disable>
      </VisitorEngagement>
      <IgnoreProviders>TDC,Ziggo,Nianet A/S (gorrissenfederspiel.com)</IgnoreProviders>
      <LeadsListKeepTemporarilyApproved>True</LeadsListKeepTemporarilyApproved>
      <EmailEngagement>
        <OpenMail>5</OpenMail>
        <ClickLink>10</ClickLink>
        <AddingProductsToCart>20</AddingProductsToCart>
        <SigningNewsletter>16</SigningNewsletter>
        <UnsubscribesNewsletter>-20</UnsubscribesNewsletter>
      </EmailEngagement>
      <EmailMarketing>
        <DefaultRecipientsListCount>-1</DefaultRecipientsListCount>
      </EmailMarketing>
    </OMC>
    <ImportExport>
      <checkToken>False</checkToken>
    </ImportExport>
    <UserManagement>
      <EncryptNewPasswords>true</EncryptNewPasswords>
      <UploadedImages>
        <EnableMaxWidth>False</EnableMaxWidth>
        <EnableMaxHeight>False</EnableMaxHeight>
        <DefineWhere>Globally</DefineWhere>
        <ImagesFolder>/Files</ImagesFolder>
        <MaxWidth>
        </MaxWidth>
        <MaxHeight>
        </MaxHeight>
      </UploadedImages>
      <UploadedCustomFiles>
        <DefineWhere>OnUser</DefineWhere>
        <FilesFolder>/Files</FilesFolder>
      </UploadedCustomFiles>
      <ExtranetPasswordSecurity>
        <PeriodLoginFailure>10</PeriodLoginFailure>
        <BlockingPeriod>10</BlockingPeriod>
        <LoginAttempts>3</LoginAttempts>
        <SecurityEnable>False</SecurityEnable>
      </ExtranetPasswordSecurity>
      <UserSmartSearchesCahceRecalculatingInterval>1</UserSmartSearchesCahceRecalculatingInterval>
    </UserManagement>
    <LanguageManagement>
      <DeactivateParagraphOnNew>False</DeactivateParagraphOnNew>
      <DeactivatePageOnNew>False</DeactivatePageOnNew>
      <AllowNewParagraphs>False</AllowNewParagraphs>
      <AllowGlobalParagraphs>False</AllowGlobalParagraphs>
      <AllowNewPages>1</AllowNewPages>
      <InheritPageChanges>1</InheritPageChanges>
      <InheritParagraphChanges>False</InheritParagraphChanges>
      <CompareParagraphAsText>False</CompareParagraphAsText>
      <UseAreaNamesForDropdowns>False</UseAreaNamesForDropdowns>
    </LanguageManagement>
  </Modules>
  <System>
    <cdn>
      <active>False</active>
      <host>
      </host>
    </cdn>
    <MailServer>
      <Type>smtp</Type>
      <Server>smtp.dynamic-systems.lan</Server>
      <DoNotUsePickup>False</DoNotUsePickup>
      <Port>
      </Port>
      <Username>
      </Username>
      <Password>
      </Password>
      <UseSll>False</UseSll>
    </MailServer>
    <ActiveDirectory>
      <ADSI-Domain>
      </ADSI-Domain>
      <UserName>
      </UserName>
      <Password>
      </Password>
      <ADSI-Domain2>
      </ADSI-Domain2>
    </ActiveDirectory>
    <Database>
      <Password>wrap</Password>
      <Type>ms_sqlserver</Type>
      <UserName>wrap</UserName>
      <Database>wrap</Database>
      <SQLServer>MICHAEL-PC\SQLEXPRESS</SQLServer>
      <DWWebIP>
      </DWWebIP>
      <SQLServer2>
      </SQLServer2>
      <Database2>
      </Database2>
      <UserName2>
      </UserName2>
      <Password2>
      </Password2>
      <IntegratedSecurity>False</IntegratedSecurity>
      <ConnectionString>
      </ConnectionString>
      <ConnectionString2>
      </ConnectionString2>
      <Translation>
        <ConnectionString>
        </ConnectionString>
        <UserName>
        </UserName>
        <Database>
        </Database>
        <SQLServer>
        </SQLServer>
        <Password>
        </Password>
      </Translation>
      <DateFormat>
      </DateFormat>
    </Database>
    <Version>
      <CurrentVersion>8.7.0.1</CurrentVersion>
      <Osmium>False</Osmium>
      <Oem>False</Oem>
      <LightPageCount>
      </LightPageCount>
      <LimitWebsiteCount>10</LimitWebsiteCount>
      <LimitSubscriberCount>500</LimitSubscriberCount>
      <LimitPageCount>1000</LimitPageCount>
      <LimitItemsCount>
      </LimitItemsCount>
      <LimitLanguageWebSitesCount>
      </LimitLanguageWebSitesCount>
    </Version>
    <Url>
      <UseSearchEngineFriendlyUrl>False</UseSearchEngineFriendlyUrl>
      <Type>Path</Type>
      <TypePageID>
        <Prefix>Page</Prefix>
      </TypePageID>
      <UseAreaNameInPath>False</UseAreaNameInPath>
      <ParseContentURL>True</ParseContentURL>
      <TrimSpaces>Hyphen</TrimSpaces>
      <EmailMunging>False</EmailMunging>
      <CaseInsensitive>True</CaseInsensitive>
      <DisableRobotsOnDwUrl>True</DisableRobotsOnDwUrl>
      <UniqueForEachLanguage>False</UniqueForEachLanguage>
      <DisableRobotsOnPrinterFriendly>False</DisableRobotsOnPrinterFriendly>
      <ParseContentURLWithParamsMethod>Slashes</ParseContentURLWithParamsMethod>
      <EnsureUniquePath>True</EnsureUniquePath>
      <UseAreaRegionalInPath>False</UseAreaRegionalInPath>
      <ParseContentURLWithParams>False</ParseContentURLWithParams>
      <UseCanoncial>True</UseCanoncial>
      <NoAreaName>True</NoAreaName>
      <UrlInlcudeAreaType>NoAreaName</UrlInlcudeAreaType>
      <PathEncode>False</PathEncode>
      <Providers>Dynamicweb.Frontend.UrlProviders.ItemTypeProvider,Dynamicweb.Frontend.UrlProviders.eComGroupPathProvider,Dynamicweb.Frontend.UrlProviders.eComProductAndVariantProvider</Providers>
      <ReplaceSlash>True</ReplaceSlash>
      <LatinNormalize>True</LatinNormalize>
      <AmpEncode>False</AmpEncode>
      <UseStrictURLRecognition>False</UseStrictURLRecognition>
      <Page404ForProductsNotInWebsiteShop>False</Page404ForProductsNotInWebsiteShop>
      <PlaceAllPagesInRoot>False</PlaceAllPagesInRoot>
      <Page404ForProductsNotInWebsiteLang>False</Page404ForProductsNotInWebsiteLang>
      <ExtensionLess>True</ExtensionLess>
      <UseCanonicalInEcommerce>False</UseCanonicalInEcommerce>
      <IncludeProductIdInUrlNames>False</IncludeProductIdInUrlNames>
      <Providersdd1ba1872df91985ed1ca4cde2dfe669>
      </Providersdd1ba1872df91985ed1ca4cde2dfe669>
      <Providerse6a7f8a2f42cc35979973da8dfb10720>
      </Providerse6a7f8a2f42cc35979973da8dfb10720>
      <BuildUrlsOnApplicationStart>False</BuildUrlsOnApplicationStart>
      <Providersa4187e6d3f147449569e124baa60ca2c>
      </Providersa4187e6d3f147449569e124baa60ca2c>
      <Providers2377be3c2ad9b435ba277a73f0f1ca76>
      </Providers2377be3c2ad9b435ba277a73f0f1ca76>
      <UniqueForEachMasterWebsite>False</UniqueForEachMasterWebsite>
    </Url>
    <http>
      <DisableBaseHrefPort>False</DisableBaseHrefPort>
      <DisableSQLInjectionCheck>False</DisableSQLInjectionCheck>
      <Compression>
        <Type>gzip</Type>
      </Compression>
      <AddLastModifiedHeader>False</AddLastModifiedHeader>
    </http>
    <SEO>
      <verifyv1>
      </verifyv1>
    </SEO>
    <Security>
      <FormAntiSpam>False</FormAntiSpam>
      <FormAntiSpamReportTo>
      </FormAntiSpamReportTo>
      <AngelLocked>False</AngelLocked>
      <DoNotBanIps>True</DoNotBanIps>
      <SQLInjectionSkip>Nicolai</SQLInjectionSkip>
    </Security>
    <InstalledSolutions>cms,cmsProfessional2014;ecom,ecomProfessional2014;</InstalledSolutions>
    <Searching>
      <EntryIndexingDelay>0</EntryIndexingDelay>
      <AlertEmailSendParams>3</AlertEmailSendParams>
      <EnableAutoUpdate>True</EnableAutoUpdate>
      <AutoUpdateDelay>0</AutoUpdateDelay>
      <EnableQueue>True</EnableQueue>
      <IndexingDelay>0</IndexingDelay>
      <IndexingRetryCount>0</IndexingRetryCount>
      <IndexingBackupUpdate>False</IndexingBackupUpdate>
      <TryRecoverCorruptedIndex>False</TryRecoverCorruptedIndex>
      <IndexingBackupSwitch>False</IndexingBackupSwitch>
      <AdvancedLogging>False</AdvancedLogging>
      <UseVariantCombinationCache>False</UseVariantCombinationCache>
    </Searching>
    <Filesystem>
      <ImagesFolderName>Images</ImagesFolderName>
      <FilesFolderName>
      </FilesFolderName>
    </Filesystem>
    <dblgnforna>False</dblgnforna>
    <dblgnfornafe>False</dblgnfornafe>
    <Clustering>
      <LocalMachineName>NP_E6420</LocalMachineName>
      <LocalUrl>
      </LocalUrl>
      <RemoteMachineName>
      </RemoteMachineName>
      <RemoteUrl>
      </RemoteUrl>
    </Clustering>
    <dblgnfornafemsg>
    </dblgnfornafemsg>
    <ExternalServices>
      <WordstreamKeywordSuggestion>
        <UserName>
        </UserName>
        <Password>
        </Password>
      </WordstreamKeywordSuggestion>
    </ExternalServices>
    <AddIns>
      <AllowLoad>True</AllowLoad>
    </AddIns>
    <LicenseConfiguration>
      <ExtraShops>2</ExtraShops>
      <IntegrationFW>0</IntegrationFW>
      <PersonalizationLicense>0</PersonalizationLicense>
      <EmailMarketingSubscribers>500</EmailMarketingSubscribers>
      <AdditionalWebsites>
      </AdditionalWebsites>
      <UpgradeProducts>0</UpgradeProducts>
    </LicenseConfiguration>
  </System>
  <Ecom>
    <Picture>
      <NoPicture>
        <Medium>Images/Ecom/missing_image.jpg</Medium>
        <Large>Images/Ecom/missing_image.jpg</Large>
        <Small>Images/Ecom/missing_image.jpg</Small>
        <Large_path>/Files/Images/Ecom/missing_image.jpg</Large_path>
        <Medium_path>/Files/Images/Ecom/missing_image.jpg</Medium_path>
        <Small_path>/Files/Images/Ecom/missing_image.jpg</Small_path>
      </NoPicture>
      <Autoscale>
        <Medium>
          <Height>
          </Height>
          <Width>
          </Width>
          <Active>False</Active>
        </Medium>
        <Large>
          <Height>
          </Height>
          <Active>False</Active>
          <Width>
          </Width>
        </Large>
        <Small>
          <Active>False</Active>
          <Width>
          </Width>
          <Height>
          </Height>
        </Small>
        <UseMindworking>False</UseMindworking>
      </Autoscale>
      <ImagePattern>/Images/Ecom/Products/{ProductNumber}.jpg</ImagePattern>
      <Group>
        <NoPicture>
          <Small>
          </Small>
          <Small_path>
          </Small_path>
          <Large>
          </Large>
          <Large_path>
          </Large_path>
        </NoPicture>
      </Group>
    </Picture>
    <Order>
      <ShippingFee>
        <UseDeliveryCountryOnShippingFee>False</UseDeliveryCountryOnShippingFee>
        <IncludeVATOnShippingFee>False</IncludeVATOnShippingFee>
      </ShippingFee>
      <ConfirmMail>
        <Method>
        </Method>
      </ConfirmMail>
      <PaymentFee>
        <UseDeliveryCountryOnPaymentFee>False</UseDeliveryCountryOnPaymentFee>
        <IncludeVATOnPaymentFee>False</IncludeVATOnPaymentFee>
      </PaymentFee>
      <ShowOldTrackAndTraceField>False</ShowOldTrackAndTraceField>
      <ConsolidateTaxesForProducts>False</ConsolidateTaxesForProducts>
      <ConsolidateTaxesForOrder>False</ConsolidateTaxesForOrder>
      <AllowEditOrderForUsers>on</AllowEditOrderForUsers>
      <VAT>
        <UseDeliveryCountry>False</UseDeliveryCountry>
      </VAT>
      <AllowExceedOriginalOrderPrice>on</AllowExceedOriginalOrderPrice>
      <DisableDeleteButtonForOrders>False</DisableDeleteButtonForOrders>
    </Order>
    <Cookie>
      <SaveLastUsedCustomerChoicesMade>True</SaveLastUsedCustomerChoicesMade>
      <DaysToSave>30</DaysToSave>
      <SaveLastUsedCustomerData>True</SaveLastUsedCustomerData>
    </Cookie>
    <ProductGroup>
      <CacheParagraph>False</CacheParagraph>
      <CacheProductCollection>False</CacheProductCollection>
      <CacheProductCollectionMinutes>15</CacheProductCollectionMinutes>
    </ProductGroup>
    <Group>
      <ShowProductCountInTree>True</ShowProductCountInTree>
      <ShowProductNumberInTree>True</ShowProductNumberInTree>
      <ShowShopNameForRelatedGroups>False</ShowShopNameForRelatedGroups>
    </Group>
    <Product>
      <DontAllowLinksToProductIfNotActive>True</DontAllowLinksToProductIfNotActive>
      <ProductNotActivePage>
      </ProductNotActivePage>
      <DontShowProductIfHasNoPrice>False</DontShowProductIfHasNoPrice>
      <DontShowProductIfNotOnStock>False</DontShowProductIfNotOnStock>
      <DontUseDefaultLanguageIsNoProductExists>True</DontUseDefaultLanguageIsNoProductExists>
      <DontShowVariantIfNotOnStock>False</DontShowVariantIfNotOnStock>
      <ShowProductCostField>False</ShowProductCostField>
      <DontAllowLinksToVariantIfNotActive>False</DontAllowLinksToVariantIfNotActive>
      <ActivateProductsOnAllLanguageVersions>False</ActivateProductsOnAllLanguageVersions>
      <UseLongDescriptionIfShortDescriptionIsEmpty>False</UseLongDescriptionIfShortDescriptionIsEmpty>
      <DontShowVariantIfHasNoPrice>False</DontShowVariantIfHasNoPrice>
      <MinutesReserved>0</MinutesReserved>
      <ReserveMode>modeCheckout</ReserveMode>
      <ShowVariantDefault>False</ShowVariantDefault>
      <BulkEditForProductVariant>False</BulkEditForProductVariant>
      <ShowBackCatalogFields>False</ShowBackCatalogFields>
    </Product>
    <PageTitle>
      <Fix>PRE</Fix>
      <ShowProductName>False</ShowProductName>
      <Seperator>
      </Seperator>
      <RemoveOldTitle>False</RemoveOldTitle>
      <ChangeTitle>False</ChangeTitle>
    </PageTitle>
    <Unit>
      <Volume>m³</Volume>
      <Weight>kg</Weight>
    </Unit>
    <ProductLanguageControl>
      <Variant>
        <ProductImageLarge>True</ProductImageLarge>
        <ProductActive>True</ProductActive>
        <ProductLongDescription>True</ProductLongDescription>
        <ProductVolume>True</ProductVolume>
        <ProductStock>True</ProductStock>
        <ProductImageSmall>True</ProductImageSmall>
        <ProductStockGroup>True</ProductStockGroup>
        <ProductWeight>True</ProductWeight>
        <ProductName>True</ProductName>
        <ProductPrice>False</ProductPrice>
        <ProductLink1>True</ProductLink1>
        <ProductShortDescription>True</ProductShortDescription>
        <ProductVATGroup>True</ProductVATGroup>
        <ProductNumber>True</ProductNumber>
        <ProductLink2>True</ProductLink2>
        <test1>True</test1>
        <croporigin>True</croporigin>
        <quantity>True</quantity>
        <ProductPeriod>True</ProductPeriod>
        <newproduct>True</newproduct>
        <ProductManufacturer>True</ProductManufacturer>
        <ProductImageMedium>True</ProductImageMedium>
        <discount>False</discount>
        <relationgroup>False</relationgroup>
        <TaxCode>False</TaxCode>
        <ItemCode>False</ItemCode>
        <rims>False</rims>
        <HideForGroup>True</HideForGroup>
        <ProductDefaultPoints>False</ProductDefaultPoints>
        <sliderfoto1>True</sliderfoto1>
        <ProductStockGroupID>True</ProductStockGroupID>
        <ProductVatGrpID>True</ProductVatGrpID>
        <ProductManufacturerID>True</ProductManufacturerID>
        <ProductPeriodID>True</ProductPeriodID>
      </Variant>
      <Language>
        <ProductManufacturer>True</ProductManufacturer>
        <newproduct>True</newproduct>
        <ProductName>True</ProductName>
        <ProductLongDescription>True</ProductLongDescription>
        <quantity>True</quantity>
        <ProductPrice>True</ProductPrice>
        <ProductShortDescription>True</ProductShortDescription>
        <ProductVolume>True</ProductVolume>
        <ProductNumber>True</ProductNumber>
        <test1>True</test1>
        <ProductStockGroup>True</ProductStockGroup>
        <ProductPeriod>True</ProductPeriod>
        <ProductImageLarge>True</ProductImageLarge>
        <croporigin>True</croporigin>
        <ProductLink1>True</ProductLink1>
        <ProductLink2>True</ProductLink2>
        <ProductStock>True</ProductStock>
        <ProductImageSmall>True</ProductImageSmall>
        <ProductActive>True</ProductActive>
        <ProductImageMedium>True</ProductImageMedium>
        <ProductWeight>True</ProductWeight>
        <ProductVATGroup>True</ProductVATGroup>
        <discount>False</discount>
        <rims>False</rims>
        <relationgroup>False</relationgroup>
        <TaxCode>False</TaxCode>
        <ItemCode>False</ItemCode>
        <HideForGroup>True</HideForGroup>
        <ProductDefaultPoints>False</ProductDefaultPoints>
        <sliderfoto1>True</sliderfoto1>
        <ProductStockGroupID>True</ProductStockGroupID>
        <ProductVatGrpID>True</ProductVatGrpID>
        <ProductManufacturerID>True</ProductManufacturerID>
        <ProductPeriodID>True</ProductPeriodID>
      </Language>
      <ChoicesMade>True</ChoicesMade>
    </ProductLanguageControl>
    <Cart>
      <SkipMethodStep>False</SkipMethodStep>
      <StepValidate>False</StepValidate>
      <UseDefaultPayment>on</UseDefaultPayment>
      <MakeNewCartWhenCartIsOrderAndIsManipulated>False</MakeNewCartWhenCartIsOrderAndIsManipulated>
      <UseDefaultShipping>on</UseDefaultShipping>
      <SavedForLaterValidTime>1</SavedForLaterValidTime>
      <RecalculateOnUserLogin>True</RecalculateOnUserLogin>
      <SkipPaymentGateway>False</SkipPaymentGateway>
      <DisableBackStepValidation>False</DisableBackStepValidation>
      <OrganizeDiscountAndTaxOrderLines>False</OrganizeDiscountAndTaxOrderLines>
      <KeepCartInContext>on</KeepCartInContext>
      <UsePreviousCartInsteadOfNewCart>on</UsePreviousCartInsteadOfNewCart>
      <AllowDifferentContextDates>False</AllowDifferentContextDates>
    </Cart>
    <UseNew>True</UseNew>
    <C5>
      <WriteOrderToFile>false</WriteOrderToFile>
      <OrderFilePath>
      </OrderFilePath>
      <FileExtension>C5</FileExtension>
    </C5>
    <ProductCategories>
      <HasBeenConverted>True</HasBeenConverted>
    </ProductCategories>
    <Navigation>
      <ApplyOnliyIfPageIsInPath>False</ApplyOnliyIfPageIsInPath>
      <EnableNavigationGroupSorting>False</EnableNavigationGroupSorting>
      <MaxNumberOfProducts>10</MaxNumberOfProducts>
      <CacheProductsMinutes>10</CacheProductsMinutes>
      <SortProductsByName>False</SortProductsByName>
      <ApplyStartAndEndLevelToNavigation>False</ApplyStartAndEndLevelToNavigation>
    </Navigation>
    <RelatedProducts>
      <LimitOfLinksToAppearOnTheList>5</LimitOfLinksToAppearOnTheList>
    </RelatedProducts>
    <Users>
      <IncludeShopIdInExtranetLogIn>on</IncludeShopIdInExtranetLogIn>
    </Users>
    <Price>
      <List>
        <UseCustomColumns>False</UseCustomColumns>
        <CustomColumns>
        </CustomColumns>
        <UseCustomOrder>False</UseCustomOrder>
        <CustomOrder>
        </CustomOrder>
      </List>
      <AllowNegativeOrderTotalPrice>False</AllowNegativeOrderTotalPrice>
      <UseSalesTaxGroupRateAsSystemTax>False</UseSalesTaxGroupRateAsSystemTax>
      <PricesInDbIncludesVAT>False</PricesInDbIncludesVAT>
      <RoundPricesWithVAT>True</RoundPricesWithVAT>
      <CalculatePercentShippingFeeInclVAT>False</CalculatePercentShippingFeeInclVAT>
      <CalculatePaymentFeeInclShippingFee>False</CalculatePaymentFeeInclShippingFee>
      <PricesInDbVAT>25</PricesInDbVAT>
      <AdvancedSettings>
        <ProductCatalogFilteringByPriceMatrix>False</ProductCatalogFilteringByPriceMatrix>
      </AdvancedSettings>
    </Price>
    <Integration>
      <DisableCreationNewProductVariant>False</DisableCreationNewProductVariant>
      <DisableCreationNewGroups>False</DisableCreationNewGroups>
      <EditGroupId>False</EditGroupId>
    </Integration>
    <Required>
      <CommonFields>
        <ProductName>False</ProductName>
        <ProductNumber>True</ProductNumber>
        <ProductShortDescription>False</ProductShortDescription>
        <ProductLongDescription>False</ProductLongDescription>
        <ProductImageSmall>False</ProductImageSmall>
        <ProductImageMedium>False</ProductImageMedium>
        <ProductImageLarge>False</ProductImageLarge>
        <ProductLink1>False</ProductLink1>
        <ProductLink2>False</ProductLink2>
        <ProductStock>False</ProductStock>
        <ProductStockGroup>False</ProductStockGroup>
        <ProductPrice>False</ProductPrice>
        <ProductWeight>False</ProductWeight>
        <ProductVolume>False</ProductVolume>
        <ProductVATGroup>False</ProductVATGroup>
        <ProductManufacturer>False</ProductManufacturer>
        <ProductActive>False</ProductActive>
        <ProductPeriod>False</ProductPeriod>
        <ProductDefaultPoints>False</ProductDefaultPoints>
      </CommonFields>
      <ProductFields>
        <newproduct>False</newproduct>
        <quantity>False</quantity>
        <croporigin>False</croporigin>
        <rims>False</rims>
        <discount>False</discount>
        <relationgroup>False</relationgroup>
        <ItemCode>False</ItemCode>
        <TaxCode>False</TaxCode>
        <HideForGroup>False</HideForGroup>
      </ProductFields>
      <ProductCategories>
        <Bikes.Frame_size>False</Bikes.Frame_size>
        <Bikes.Wheel_size>False</Bikes.Wheel_size>
        <Clothes.Fabric>False</Clothes.Fabric>
      </ProductCategories>
    </Required>
    <ProductCategoriesLanguageControl>
      <Language>
        <Bikes.Frame_size>False</Bikes.Frame_size>
        <Bikes.Wheel_size>False</Bikes.Wheel_size>
        <Clothes.Fabric>False</Clothes.Fabric>
      </Language>
      <Variant>
        <Bikes.Frame_size>False</Bikes.Frame_size>
        <Bikes.Wheel_size>False</Bikes.Wheel_size>
        <Clothes.Fabric>False</Clothes.Fabric>
      </Variant>
    </ProductCategoriesLanguageControl>
    <LimitShopCount>3</LimitShopCount>
    <LimitProductCount>1000</LimitProductCount>
    <LimitCountryCount>
    </LimitCountryCount>
    <LoyaltyPoints>
      <LastExpirationAddInRun>2015-9-21 11:25:5</LastExpirationAddInRun>
    </LoyaltyPoints>
    <GiftCards>
      <ExpirationPeriod>24</ExpirationPeriod>
    </GiftCards>
  </Ecom>
  <ItemTypes>
    <MetadataSource>files</MetadataSource>
    <UseLocalization>true</UseLocalization>
    <DefaultLanguage>
    </DefaultLanguage>
    <HasBeenConverted>True</HasBeenConverted>
  </ItemTypes>
</Globalsettings>