//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// CustomDealersearch_Edit class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class CustomDealersearch_Edit
{

    /// <summary>
    /// GroupBoxStart1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.GroupBoxStart GroupBoxStart1;

    /// <summary>
    /// SortByDealerSearchDealerName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortByDealerSearchDealerName;

    /// <summary>
    /// SortByDealerSearchDealerAdress control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortByDealerSearchDealerAdress;

    /// <summary>
    /// SortByDealerSearchDealerZip control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortByDealerSearchDealerZip;

    /// <summary>
    /// SortByDealerSearchDealerCity control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortByDealerSearchDealerCity;

    /// <summary>
    /// SortByDealerSearchDealerCountry control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortByDealerSearchDealerCountry;

    /// <summary>
    /// SortOrderASC control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortOrderASC;

    /// <summary>
    /// SortOrderDESC control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.RadioButton SortOrderDESC;

    /// <summary>
    /// GroupBoxEnd1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.GroupBoxEnd GroupBoxEnd1;

    /// <summary>
    /// GroupBoxStart2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.GroupBoxStart GroupBoxStart2;

    /// <summary>
    /// SearchTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.FileManager SearchTemplate;

    /// <summary>
    /// ListTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.FileManager ListTemplate;

    /// <summary>
    /// ListElementTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.FileManager ListElementTemplate;

    /// <summary>
    /// ElementTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.FileManager ElementTemplate;

    /// <summary>
    /// GroupBoxEnd2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.GroupBoxEnd GroupBoxEnd2;

    /// <summary>
    /// GroupBoxStart3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.GroupBoxStart GroupBoxStart3;

    /// <summary>
    /// CategoryCell control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell CategoryCell;

    /// <summary>
    /// GroupBoxEnd3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dynamicweb.Controls.GroupBoxEnd GroupBoxEnd3;
}
